services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: uberzettle
      POSTGRES_USER: uberzettle
      POSTGRES_PASSWORD: uberzettleisawesome
    ports:
      - '5432:5432'
