interface Node {
    """The ID of the object, which must be globally unique."""
    id: ID!
}

type Idea implements Node {
    id: ID!
    idea: String!
}

type PageInfo {
    hasNextPage: Boolean!
    hasPreviousPage: Boolean!
    startCursor: String
    endCursor: String
}

input IdeaCreateInput{
    idea: String!
}

type IdeaEdge {
    cursor: String!
    node: Idea!
}
type IdeaConnection {
    edges: [IdeaEdge!]!
    pageInfo: PageInfo!
}

type Mutation {
    ideaCreate( newIdea: IdeaCreateInput): Idea
}
type Query {
    """Fetches an object given its global ID."""
    node(id: ID!): Node
    ideas(first: Int
        after: ID
        last: Int
        before: ID): IdeaConnection!
}
