spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  graphql:
    schema:
      locations: classpath*:graphql/**/
    http:
      path: /graphql
    graphiql:
      enabled: true

logging:
  level:
    org.springframework.boot.autoconfigure.graphql: DEBUG
    org.springframework.graphql: trace
    org.springframework.web.servlet.function: INFO

com:
  nsfwllc:
    uberzettlegraphql:
      controllers:
        defaultPageSize: 5
        maxPageSize: 10
